controller_names:
  - ur5e_controller
  
ur5e_controller:
  action_ns: ur5e
  type: FollowJointTrajectory
  default: false
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - robotiqrobotiq_85_left_knuckle_joint
